routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('docs',function () {
    return view('pages/project_docs');
});

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

Route::get('/', function () {
    return view('pages/index');
});

/* Testing */
Route::get('/test', 'TestController@index');

/* PMS routes */
Route::resource('hotels', 'HotelController');
Route::resource('rooms', 'RoomController');
Route::resource('agents', 'AgentController');

resources/views/partials/_add_agent.blade.php
<?php
/**
 *
 * Project: pms
 * Generated: 22-09-2017 @ 11:31 PM
 *
 * User:        Mr. Fulop
 * Created by:  Online Promoters
 * Email:       online@promoters.ro
 * Web:         https://online.promoters.ro/
 */
?>
<div class="container">
    <h2>Add new cleaning agent</h2><br  />
    <form method="post" action="{{route('agents.index')}}">
        {{csrf_field()}}
        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <label for="name">Name*:</label>
                <input type="text" class="form-control" name="name">
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">Room charge*</div>
        </div>
            @foreach(config('data.room_types') as $type)
            <div class="row">
                <div class="col-md-4"></div>
                <div class="form-group col-md-4">
                    <label for="prices">{{$type}}:</label>
                    <input type="text" class="form-control" name="prices[]" value="">
                </div>
            </div>
            @endforeach

        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <button type="submit" class="btn btn-success" style="margin-left:38px">Add agent</button>
            </div>
        </div>
    </form>
</div>

resources/views/partials/_add_hotel.blade.php
<?php
/**
 *
 * Project: pms
 * Generated: 22-09-2017 @ 1:31 PM
 *
 * User:        Mr. Fulop
 * Created by:  Online Promoters
 * Email:       online@promoters.ro
 * Web:         https://online.promoters.ro/
 */
?>

<div class="container">
    <h2>Add new hotel</h2><br  />
    <form method="post" action="{{route('hotels.index')}}">
        {{csrf_field()}}
        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <label for="name">Name:</label>
                <input type="text" class="form-control" name="name">
            </div>
        </div>

        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <label for="address">Address:</label>
                <textarea class="form-control" name="address"></textarea>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <label for="description">Description:</label>
                <textarea class="form-control" name="description"></textarea>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <button type="submit" class="btn btn-success" style="margin-left:38px">Add hotel</button>
            </div>
        </div>
    </form>
</div>

resources/views/partials/_add_room.blade.php
<?php
/**
 *
 * Project: pms
 * Generated: 22-09-2017 @ 5:01 PM
 *
 * User:        Mr. Fulop
 * Created by:  Online Promoters
 * Email:       online@promoters.ro
 * Web:         https://online.promoters.ro/
 */
?>
<div class="container">
    <h2>Add new room to hotel {{ $hotel->name }}</h2><br  />
    <form method="post" action="{{route('rooms.index',['hotel_id'=>$hotel->id])}}">
        {{csrf_field()}}

        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <label for="number">Number:</label>
                <input type="text" class="form-control" name="number">
            </div>
        </div>

        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <label for="name">Floor:</label>
                <input type="text" class="form-control" name="floor">
            </div>
        </div>

        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <label for="type">Type</label>
                <select class="form-control" name="type">
                    @php
                        foreach(config('data.room_types') as $type)
                        {
                            echo  '<option value="'.$type.'">'.ucfirst($type).'</option>';
                        }
                    @endphp
                </select>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <label for="agents">Cleaning agents</label>
                <select name="agents[]" id="SelectRooms" class="selected" data-placeholder="{{ config('messages.add_cleaner') }}" multiple="multiple" >
                <option></option>
                </select>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <button type="submit" class="btn btn-success" style="margin-left:38px">Add room</button>
            </div>
        </div>
    </form>
</div>

@push('javascript')
    <script type="application/javascript">

        $(document).ready(function()
        {
            //implementing select2 for cleaning agents
            $('.selected').select2({
                minimumResultsForSearch: -1,
                placeholder: function(){
                    $(this).data('placeholder');
                },
                allowClear: true,
                data: {!! json_encode($all_agents) !!}, //our data for feeding the select2 Cleaners Selection
                width: "80%",
                tags: true,
                tokenSeparators: [','],
            }).on('change', function (e) {

                var data = $(this).select2('data');
                //we need the room id to update the agents data
                var url = $(this).data('url');
                var data_to_send = [];

                $.each(data, function( index, value ) {
                    data_to_send.push({'id':value.id,'name':value.text});
                });

                console.log(data_to_send);

            });

        });

    </script>
@endpush

resources/views/partials/_display_agents.blade.php
<?php
/**
 *
 * Project: pms
 * Generated: 21-09-2017 @ 12:45 PM
 *
 * User:        Mr. Fulop
 * Created by:  Online Promoters
 * Email:       online@promoters.ro
 * Web:         https://online.promoters.ro/
 */
?>

<h1> Cleaning agents available</h1>
<div class="header">{!! $prediction !!}</div>
{{--submenu for rooms--}}
@include('partials._menu',$items)
<div class="container">
    <div class="agents-listing">
        @if(isset($data) && count($data)>0)
            <table class="agents display" cellspacing="0" width="100%">
                <thead>
                <tr>
                    <th>Agent name</th>
                    <th>Agent average price (Lei)</th>
                    <th>Agent workload (%)</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
                </thead>
                <tbody>
                @foreach($data as $agent_id => $agent_data)
                    <tr>
                        <td data-pk="{{ $agent_id }}" class="editable">{{ $agent_data['name'] }}</td>
                        <td>{{ $agent_data['avg_price'] }}</td>
                        <td>{{ $agent_data['workload'] }}</td>
                        <td><a href="{{action('AgentController@edit', $agent_id)}}" class="btn btn-warning">Edit</a></td>
                        <td>
                            <form action="{{action('AgentController@destroy', $agent_id)}}" method="post">
                                {{csrf_field()}}
                                <input name="_method" type="hidden" value="DELETE">
                                <button class="delete btn btn-danger" type="submit">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach

                </tbody>
            </table>
        @else
            <i>{{ config('messages.no_agents_avail') }}</i>
        @endif
    </div>

    @push('javascript')
        <script type="application/javascript">

            $(document).ready(function() {

                $.fn.editable.defaults.mode = 'inline';
                $('.editable').editable({
                    type: 'text',
                    url: '{{ route('agents.store') }}',
                    title: 'Edit agent'
                });


                //datatables
                $(document).ready(function() {
                    $('.agents').DataTable({
                        "order": [[ 2, "asc" ]] //we can order it on the client side to save server resources
                    } );
                } );
            });

        </script>
@endpush

resources/views/partials/_display_rooms.blade.php
<?php
/**
 *
 * Project: pms
 * Generated: 21-09-2017 @ 12:25 PM
 *
 * User:        Mr. Fulop
 * Created by:  Online Promoters
 * Email:       online@promoters.ro
 * Web:         https://online.promoters.ro/
 */

//setting up the hotel rooms needed for listing
if(isset($hotel)) $rooms = $hotel->rooms;

?>

<h1> Rooms available @ {{ $hotel->name }}</h1>
{{--submenu for rooms--}}
@include('partials._menu',$items)

<div class="container">
    <div class="room-listing">
        @if(isset($rooms) && count($rooms)>0)
            <table id="Rooms-{{$hotel->name}}" class="rooms display" cellspacing="0" width="100%">
                <thead>
                <tr>
                    <th>Room number</th>
                    <th>Floor</th>
                    <th>Room type</th>
                    <th>Cleaning agents</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
                </thead>
                <tbody>
                @foreach($rooms as $room)
                    <tr>
                        <td>{{ $room->number }}</td>
                        <td>{{ $room->floor }}</td>
                        <td>{{ $room->type }}</td>
                        <td>
                            <div class="agents">
                                <select name="agents" id="SelectRooms-{{$hotel->name}}" class="selected" data-placeholder="{{ config('messages.add_cleaner') }}" multiple="multiple" data-url="{{ route('rooms.show',['id' => $room->id]) }}">
                                    @if(count($room->agents) > 0)
                                        @foreach($room->agents->unique() as $agent)
                                            <option selected="selected" value="{{$agent->id}}">{{$agent->name}}</option>
                                        @endforeach
                                    @endif
                                </select>
                            </div>
                        </td>
                        <td><a href="{{action('RoomController@edit', $room->id)}}" class="btn btn-warning">Edit</a></td>
                        <td>
                            <form action="{{action('RoomController@destroy', $room->id)}}" method="post">
                                {{csrf_field()}}
                                <input name="_method" type="hidden" value="DELETE">
                                <button class="delete btn btn-danger" type="submit">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach

                </tbody>
            </table>
        @else
            <i>{{ config('messages.no_rooms_avail') }}</i>
        @endif
    </div>

</div>


<script type="application/javascript">

    $(document).ready(function()
    {
        //implementing select2 for cleaning agents
        $('.selected').select2({
            minimumResultsForSearch: -1,
            placeholder: function(){
                $(this).data('placeholder');
            },
            allowClear: true,
            data: {!! json_encode($all_agents) !!}, //our data for feeding the select2 Cleaners Selection
            width: "80%",
            tags: true,
            tokenSeparators: [','],
        }).on('change', function (e) {

            var data = $(this).select2('data');
            //we need the room id to update the agents data
            var url = $(this).data('url');
            var data_to_send = [];

            $.each(data, function( index, value ) {
                data_to_send.push({'id':value.id,'name':value.text});
            });

            console.log(data_to_send);
            $.ajax({
                type: "PUT",
                url: url,
                data: {"agents":data_to_send},
                success:function(response) {

                    console.log(response);

                },error: function (data) {

                    var error_message = data.responseText; //default error message
                    var response = data.responseJSON;

                    alert(error_message);
                    console.log(data, response);
                }
            })
            //console.log(data_to_send);
        });

        //datatables
        $('#Rooms-{{$hotel->name}}').DataTable();

    });

</script>

resources/views/partials/_edit_agent.blade.php
<?php
/**
 *
 * Project: pms
 * Generated: 23-09-2017 @ 12:34 AM
 *
 * User:        Mr. Fulop
 * Created by:  Online Promoters
 * Email:       online@promoters.ro
 * Web:         https://online.promoters.ro/
 */
?>
<div class="container">
    <h2>Edit agent {{ $agent->name }}</h2><br  />
    <form method="post" action="{{action('AgentController@update', $agent->id)}}">
        {{csrf_field()}}
        <input name="_method" type="hidden" value="PATCH">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <label for="name">Name:</label>
                <input type="text" class="form-control" name="name" value="{{$agent->name}}">
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">Room charge*</div>
        </div>
        @php
            $preturi = array();
            if(count($agent->prices)>0)
            {
                foreach ($agent->prices as $price)
                {
                    $preturi[$price->type] = $price->price;
                }
            }
        @endphp
        @foreach(config('data.room_types') as $type)
            @php
                $pret ='';
                if(isset($preturi[$type]))
                {
                        $pret = $preturi[$type];
                }
            @endphp
           <div class="row">
                <div class="col-md-4"></div>
                <div class="form-group col-md-4">
                    <label for="prices">{{$type}}:</label>
                    <input type="text" class="form-control" name="prices[]" value="{{ $pret }}">
                </div>
            </div>
        @endforeach

        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <button type="submit" class="btn btn-success" style="margin-left:38px">Update</button>
            </div>
        </div>
    </form>
</div>

resources/views/partials/_edit_hotel.blade.php
<?php
/**
 *
 * Project: pms
 * Generated: 22-09-2017 @ 1:46 PM
 *
 * User:        Mr. Fulop
 * Created by:  Online Promoters
 * Email:       online@promoters.ro
 * Web:         https://online.promoters.ro/
 */
?>

<div class="container">
    <h2>Edit Hotel {{ $hotel->name }}</h2><br  />
    <form method="post" action="{{action('HotelController@update', $hotel->id)}}">
        {{csrf_field()}}
        <input name="_method" type="hidden" value="PATCH">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <label for="name">Name:</label>
                <input type="text" class="form-control" name="name" value="{{$hotel->name}}">
            </div>
        </div>

        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <label for="address">Address</label>
                <textarea class="form-control" name="address">{{$hotel->address}}</textarea>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <label for="address">Description</label>
                <textarea class="form-control" name="description">{{$hotel->description}}</textarea>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <button type="submit" class="btn btn-success" style="margin-left:38px">Update</button>
            </div>
        </div>
</form>
</div>

resources/views/partials/_edit_room.blade.php
<?php
/**
 *
 * Project: pms
 * Generated: 22-09-2017 @ 3:47 PM
 *
 * User:        Mr. Fulop
 * Created by:  Online Promoters
 * Email:       online@promoters.ro
 * Web:         https://online.promoters.ro/
 */
?>

<div class="container">
    <h2>Edit Room {{ $room->number }}</h2><br  />
    <form method="post" action="{{action('RoomController@update', $room->id)}}">
        {{csrf_field()}}
        <input name="_method" type="hidden" value="PATCH">

        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <label for="number">Number:</label>
                <input type="text" class="form-control" name="number" value="{{$room->number}}">
            </div>
        </div>

        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <label for="name">Floor:</label>
                <input type="text" class="form-control" name="floor" value="{{$room->floor}}">
            </div>
        </div>

        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <label for="type">Type</label>
                <select class="form-control" name="type">
                    @php
                        foreach(config('data.room_types') as $type)
                        {
                            $selected = '';
                            if($type == $room->type)
                            {
                                $selected = 'selected="selected"';
                            }

                            echo  '<option '.$selected.' value="'.$type.'">'.ucfirst($type).'</option>';
                        }
                    @endphp
                </select>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <label for="agents">Cleaning agents</label>
                    <select name="agents[]" id="SelectRooms-{{$room->id}}" class="selected" data-placeholder="{{ config('messages.add_cleaner') }}" multiple="multiple" data-url="{{ route('rooms.show',['id' => $room->id]) }}">
                        @if(count($room->agents) > 0)
                            @foreach($room->agents->unique() as $agent)
                                <option selected="selected" value="{{$agent->id}}">{{$agent->name}}</option>
                            @endforeach
                        @endif
                    </select>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <button type="submit" class="btn btn-success" style="margin-left:38px">Update</button>
            </div>
        </div>
</form>
</div>

@push('javascript')
    <script type="application/javascript">

        $(document).ready(function()
        {
            //implementing select2 for cleaning agents
            $('.selected').select2({
                minimumResultsForSearch: -1,
                placeholder: function(){
                    $(this).data('placeholder');
                },
                allowClear: true,
                data: {!! json_encode($all_agents) !!}, //our data for feeding the select2 Cleaners Selection
                width: "80%",
                tags: true,
                tokenSeparators: [','],
            }).on('change', function (e) {

                var data = $(this).select2('data');
                //we need the room id to update the agents data
                var url = $(this).data('url');
                var data_to_send = [];

                $.each(data, function( index, value ) {
                    data_to_send.push({'id':value.id,'name':value.text});
                });

                console.log(data_to_send);

                //console.log(data_to_send);
            });

        });

    </script>
@endpush

resources/views/partials/_hotel_selector.blade.php
<?php
/**
 *
 * Project: pms
 * Generated: 21-09-2017 @ 8:47 PM
 *
 * User:        Mr. Fulop
 * Created by:  Online Promoters
 * Email:       online@promoters.ro
 * Web:         https://online.promoters.ro/
 */
//todo make it better
$selected = '';
if(isset($hotel))
{
    $cur_hotel = $hotel->name;
}

?>
<div class="container">
    <div class="Hotels">
        @if(isset($hotels))
            <select class="hotels" name="hotels" data-placeholder="{{ config('messages.s2_type_hotel') }}">
                <option></option>
                @foreach($hotels as $hotel)
                    @php
                        $url = route('rooms.index',['hotel_id'=> $hotel->id]);
                    @endphp
                    @if(isset($cur_hotel) && $cur_hotel==$hotel->name)
                        <option selected="selected" data-url="{{ $url }}" value="{{$hotel->id}}">{{$hotel->name}}</option>
                        @else
                        <option data-url="{{ $url }}" value="{{$hotel->id}}">{{$hotel->name}}</option>
                    @endif

                @endforeach
            </select>
        @else
            <i>{{ config('messages.no_hotel_avail') }}</i>
        @endif
    </div>
</div>

@push('javascript')
    <script type="application/javascript">

        $(document).ready(function() {

            //implementing select2 for hotel selection
            $('.hotels').select2({
                width: "50%",
                minimumResultsForSearch: -1,
                placeholder: function(){
                    $(this).data('placeholder');
                }
            }).on("select2:select", function (e) {
                var selected = e.params.data;
                if (typeof selected !== "undefined") {
                    //var nume_hotel = selected.text;
                   // var id_hotel = selected.id;
                    var url = $(selected.element).data('url');

                    $.ajax({
                        type: "GET",
                        url: url
                        /*data: {"id":id_hotel}*/,
                        success:function(response) {

                            $("#Ajax").html(response); //update the div with the rooms listing

                                     console.log(response);

                        },error: function (data) {

                            var error_message = data.responseText; //default error message
                            var response = data.responseJSON;

                            alert(error_message);
                            console.log(data, response);
                        }
                    })

                }
            });
        });

    </script>
@endpush

resources/views/partials/_list_hotels.blade.php
<?php
/**
 *
 * Project: pms
 * Generated: 22-09-2017 @ 12:48 PM
 *
 * User:        Mr. Fulop
 * Created by:  Online Promoters
 * Email:       online@promoters.ro
 * Web:         https://online.promoters.ro/
 */
?>
<div class="container">
    <table id="HotelsListing" class="table table-striped display" cellspacing="0" width="100%">
        <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Address</th>
            <th>Description</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        @foreach($hotels as $hotel)
            <tr>
                <td>{{$hotel['id']}}</td>
                <td>{{$hotel['name']}}</td>
                <td>{{$hotel['address']}}</td>
                <td>{{$hotel['description']}}</td>
                <td><a href="{{action('HotelController@edit', $hotel['id'])}}" class="btn btn-warning">Edit</a></td>
                <td>
                    <form action="{{action('HotelController@destroy', $hotel['id'])}}" method="post">
                        {{csrf_field()}}
                        <input name="_method" type="hidden" value="DELETE">
                        <button class="delete btn btn-danger" type="submit">Delete</button>
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

@push('javascript')
    <script type="application/javascript">
    jQuery(document).ready(function() {

    $(".delete").popConfirm({
    title: "Are you sure you want to remove this record?"
    });

    });
    </script>
@endpush

resources/views/partials/_menu.blade.php
<?php
/**
 *
 * Project: pms
 * Generated: 22-09-2017 @ 10:33 AM
 *
 * User:        Mr. Fulop
 * Created by:  Online Promoters
 * Email:       online@promoters.ro
 * Web:         https://online.promoters.ro/
 */

?>
<nav class="menu">
<ul class="nav justify-content-center">
    @foreach($items as $item)

        @php
        isset($item['active']) ? $active = 'active' : $active ='';
        isset($item['id']) ? $id = "id='{$item['id']}'" : $id ='';
        @endphp

        <li class="nav-item">
            <a {!! $id !!} class="nav-link {{ $active }}" href="{{ $item['link'] }}">{{$item['title']}}</a>
        </li>
    @endforeach
</ul>
</nav>